import Image from "next/image";
import Head from "next/head";
import React from "react";
import pokedexLogo from "@/assets/images/pokedex_logo.png";
import Link from "next/link";

type LayoutProps = {
  children: React.ReactNode;
  title: string;
};

const Layout = ({ children, title }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-full fixed h-[75px] z-[9999] shadow-md bg-white">
        <div className="max-w-screen-xl mx-auto flex justify-between items-center p-3 h-full">
          <Link href="/" title="Go to home">
            {" "}
            <Image src={pokedexLogo} alt="Pokedex Logo" width={200} priority />
          </Link>

          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            // fill="red"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            // stroke="red"
            className="w-6 h-6"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M11.48 3.499a.562.562 0 011.04 0l2.125 5.111a.563.563 0 00.475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 00-.182.557l1.285 5.385a.562.562 0 01-.84.61l-4.725-2.885a.563.563 0 00-.586 0L6.982 20.54a.562.562 0 01-.84-.61l1.285-5.386a.562.562 0 00-.182-.557l-4.204-3.602a.563.563 0 01.321-.988l5.518-.442a.563.563 0 00.475-.345L11.48 3.5z"
            />
          </svg>
        </div>
      </header>
      <main className="pt-[75px] p-3">{children}</main>
    </>
  );
};

export default Layout;
