import Image from "next/image";
import Head from "next/head";
import React from "react";
import pokedexLogo from "@/assets/images/pokedex_logo.png";
import Link from "next/link";
import { StarOutlined } from "@ant-design/icons";

type LayoutProps = {
  children: React.ReactNode;
  title: string;
};

const Layout = ({ children, title }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="w-full fixed h-[75px] z-[50] shadow-md bg-white">
        <div className="max-w-screen-xl mx-auto flex justify-between items-center p-3 h-full">
          <Link href="/" title="Go to home">
            {" "}
            <Image src={pokedexLogo} alt="Pokedex Logo" width={200} priority />
          </Link>

          <Link href="/favorite" title="Favorite">
            <StarOutlined style={{ fontSize: "24px", color: "black" }} />
          </Link>
        </div>
      </header>
      <main className="pt-[75px] p-3">{children}</main>
    </>
  );
};

export default Layout;
